### ISSUE TITLE
Multiple bugs from stress testing - incidents page

### ISSUE THREAD

**Issue by pedroDergas** [Centannial-College/COMP229-XTRAK#10]
- when adding incidents with numbers in all fields it breaks - Possible Solution: Add field validation

- when adding incidents with the same title it breaks but then add the same as previous - Possible Solution: Add validation of previous titles

- when adding 2 incidents consecutively, even though the second has valid input there is a crash

- When you archive and click submit, you stay in the same incident page instead returning to list, if you click submit again it breaks - Possible Solution after archiving being redirected to list

**Comment by catgutD** [comment]
> When you archive and click submit, you stay in the same incident page instead returning to list, if you click submit again it breaks - Possible Solution after archiving being redirected to list

seems like the issue is that mongo believes that we are performing an update on the _id field which shouldn't be changed. I'm unsure if the id has changed once we archive the incident

**Comment by catgutD** [comment]
all issues resolved
